// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TimeOff.Models
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class LeaveApplicationReceived : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"LeaveApplicationReceived\",\"namespace\":\"TimeOff.Models\",\"" +
				"fields\":[{\"name\":\"Email\",\"type\":\"string\"},{\"name\":\"Department\",\"type\":\"string\"}," +
				"{\"name\":\"LeaveDurationInHours\",\"type\":\"int\"},{\"name\":\"LeaveStartDateTicks\",\"type" +
				"\":\"long\"}]}");
		private string _Email;
		private string _Department;
		private int _LeaveDurationInHours;
		private long _LeaveStartDateTicks;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return LeaveApplicationReceived._SCHEMA;
			}
		}
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				this._Email = value;
			}
		}
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				this._Department = value;
			}
		}
		public int LeaveDurationInHours
		{
			get
			{
				return this._LeaveDurationInHours;
			}
			set
			{
				this._LeaveDurationInHours = value;
			}
		}
		public long LeaveStartDateTicks
		{
			get
			{
				return this._LeaveStartDateTicks;
			}
			set
			{
				this._LeaveStartDateTicks = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Email;
			case 1: return this.Department;
			case 2: return this.LeaveDurationInHours;
			case 3: return this.LeaveStartDateTicks;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Email = (System.String)fieldValue; break;
			case 1: this.Department = (System.String)fieldValue; break;
			case 2: this.LeaveDurationInHours = (System.Int32)fieldValue; break;
			case 3: this.LeaveStartDateTicks = (System.Int64)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
